spring:
  application:
    name: NeuroCards

  datasource:
    url: jdbc:postgresql://localhost:5432/neurocards_db
    username: postgres
    password: 2611

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080